### ISSUE TITLE
Overflow on Small Screens

### ISSUE THREAD

**Issue by ghost** [MarcusOtter/needle.gg#4]
> I'm not creating a PR because this site will be rewritten with Astro soon. #1 

There's a overflow problem on small screen devices. But users with larger screen can reproduce it with zooming in. Managed to fix it with changing here to `0`.
https://github.com/MarcusOtter/needle.gg/blob/0fec5ec8d88b35a178d25c9714215b4c2b945a0d/css/index.css#L339
And also some text with icons are not fully centered.
![image](https://user-images.githubusercontent.com/83988414/149669730-3daa5f3e-6096-4e3e-b8f3-d459a4637496.png)
![image](https://user-images.githubusercontent.com/83988414/149669747-73b5640e-2e4a-4cd5-a427-fc7205e277be.png)
![image](https://user-images.githubusercontent.com/83988414/149669774-9631036b-449f-4906-828b-f858be12b4ec.png)
### Overflow
![image](https://user-images.githubusercontent.com/83988414/149669591-bbb82f64-379f-483a-8b1d-4ab6fd961494.png)

**Comment by MarcusOtter** [comment]
Thanks for bringing this to my attention! I had missed the overflow somehow. Instead of changing the position of the images, I'll set `overflow-x: hidden` so the style remains the same. The alignment of the pictures were annoying me, I'll tackle those again in the Astro rework 😄 

Fixed in https://github.com/MarcusOtter/needle.gg/commit/5de229f523bc5f85b13dc7154051d8d93d2916ec
